//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quan_Ly_Kinh_Doanh
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHONGBAN
    {
        public PHONGBAN()
        {
            this.NHANVIENs = new HashSet<NHANVIEN>();
        }
    
        public string MaPB { get; set; }
        public string TenPhong { get; set; }
        public string TruongPhong { get; set; }
    
        public virtual ICollection<NHANVIEN> NHANVIENs { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
