//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quan_Ly_Kinh_Doanh
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QuanLySieuThiEntities : DbContext
    {
        public QuanLySieuThiEntities()
            : base("name=QuanLySieuThiEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CHITIETHOADON> CHITIETHOADONs { get; set; }
        public DbSet<DANGNHAP> DANGNHAPs { get; set; }
        public DbSet<HOADON> HOADONs { get; set; }
        public DbSet<KHACHHANG> KHACHHANGs { get; set; }
        public DbSet<NHANVIEN> NHANVIENs { get; set; }
        public DbSet<PHONGBAN> PHONGBANs { get; set; }
        public DbSet<SANPHAM> SANPHAMs { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
