//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quan_Ly_Kinh_Doanh
{
    using System;
    using System.Collections.Generic;
    
    public partial class SANPHAM
    {
        public SANPHAM()
        {
            this.CHITIETHOADONs = new HashSet<CHITIETHOADON>();
        }
    
        public string MaSP { get; set; }
        public string TenSP { get; set; }
        public string DonViTinh { get; set; }
        public Nullable<double> Gia { get; set; }
        public byte[] Hinh { get; set; }
    
        public virtual ICollection<CHITIETHOADON> CHITIETHOADONs { get; set; }
    }
}
