//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quan_Ly_Kinh_Doanh
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_ChiTietHoaDon
    {
        public string MaHD { get; set; }
        public string TenSP { get; set; }
        public Nullable<int> SoLuong { get; set; }
    }
}
