//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quan_Ly_Kinh_Doanh
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_PhongBan
    {
        public string MaPB { get; set; }
        public string TenPhong { get; set; }
        public string TenTruongPhong { get; set; }
    }
}
